name: Node.js CI

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install -g @vscode/vsce
    - run: vsce package
    - run: vsce publish -p $VSCE_TOKEN
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
    - run: |
        gh release create \
          '${{ github.ref_name }}' \
          --title '${{ github.ref_name }}' \
          cyf-extension-pack-*.vsix
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        GH_TOKEN: ${{ github.token }}
