name: Node.js CI

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - run: npm install --global @vscode/vsce
    - run: vsce package --out cyf-extension-pack.vsix
    - uses: actions/upload-artifact@v4
      with:
        name: vsix-package
        path: cyf-extension-pack.vsix
        if-no-files-found: error
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [ build ]
    environment:
      name: publish
      url: https://marketplace.visualstudio.com/items?itemName=CodeYourFuture.cyf-extension-pack
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - run: npm install --global @vscode/vsce
    - uses: actions/download-artifact@v4
      with:
        name: vsix-package
    - run: vsce publish --packagePath cyf-extension-pack.vsix
      env:
        VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
    - run: |
        gh release create \
          '${{ github.ref_name }}' \
          --title '${{ github.ref_name }}' \
          cyf-extension-pack-*.vsix
      env:
        GH_TOKEN: ${{ github.token }}
